"""Build and write the export file.

Home Assistant's own diagnostics download wraps an integration's payload in an
envelope listing every custom integration installed and the Home Assistant
version. That is more than anyone needs to see in order to add support for a
device, so this integration writes its own file instead and controls every
byte of it.
"""
import json
import logging
from pathlib import Path
from typing import Any

from homeassistant.components.persistent_notification import (
    async_create as async_create_notification,
)
from homeassistant.core import HomeAssistant
from homeassistant.util import dt as dt_util

from .api import TuyaApiError, TuyaInspectorApi
from .const import DOMAIN

_LOGGER = logging.getLogger(__name__)

# Local keys allow direct control of a device on the LAN, and the records also
# carry the owner's public IP address and GPS coordinates. The device id is
# deliberately kept: it is useless without the key or the account credentials,
# and it lets whoever reads the file match it to a report.
REDACT_KEYS = {
    "local_key",
    "localkey",
    "uid",
    "uuid",
    "owner_id",
    "ownerid",
    "ip",
    "lat",
    "lon",
    "bindspaceid",
    "access_id",
    "access_secret",
    "client_id",
    "token",
    "access_token",
    "refresh_token",
}

REDACTED = "**REDACTED**"

NOTE = (
    "Generated by the Tuya Device Inspector. Local keys, account identifiers, "
    "IP address and coordinates have been removed. The device id is kept "
    "deliberately and is not sensitive on its own. Nothing about your Home "
    "Assistant installation or your other integrations is included."
)


def redact(value: Any) -> Any:
    """Walk the structure and blank anything sensitive, by key name.

    Matching is case-insensitive because Tuya is inconsistent about it: the
    device list returns localKey while the device record returns local_key.
    """
    if isinstance(value, dict):
        return {
            key: REDACTED if key.lower() in REDACT_KEYS else redact(item)
            for key, item in value.items()
        }
    if isinstance(value, list):
        return [redact(item) for item in value]
    return value


def unwrap_model(result: Any) -> Any:
    """Parse the data model, which arrives as JSON inside a JSON string.

    Left as-is if it cannot be parsed, so a change at Tuya's end costs
    readability rather than the whole export.
    """
    if not isinstance(result, dict):
        return result
    model = result.get("model")
    if not isinstance(model, str):
        return result
    try:
        return {**result, "model": json.loads(model)}
    except (ValueError, TypeError):
        _LOGGER.debug("Data model was not valid JSON; leaving it as text")
        return result


async def async_build_export(api: TuyaInspectorApi, device_id: str) -> dict:
    """Collect everything about one device, redacted.

    Each call is independent: some firmware answers one endpoint and not
    another, and a single failure should not cost the whole report.
    """
    export: dict[str, Any] = {
        "note": NOTE,
        "generated_at": dt_util.utcnow().isoformat(),
        "device_id": device_id,
    }

    sections = (
        ("device_record", api.async_get_device(device_id), False),
        ("things_data_model", api.async_get_model(device_id), True),
        ("specification", api.async_get_specification(device_id), False),
        ("current_properties", api.async_get_properties(device_id), False),
    )

    for key, coroutine, is_model in sections:
        try:
            result = await coroutine
        except TuyaApiError as err:
            _LOGGER.debug("Could not collect %s: %s", key, err)
            export[key] = {"error": str(err)}
        except Exception as err:  # noqa: BLE001 - recorded in the file itself
            _LOGGER.exception("Unexpected error collecting %s", key)
            export[key] = {"error": f"unexpected: {err}"}
        else:
            export[key] = redact(unwrap_model(result) if is_model else result)

    return export


async def async_write_export(
    hass: HomeAssistant, api: TuyaInspectorApi, device_id: str, title: str
) -> str:
    """Write the export where Home Assistant will serve it, and say so.

    Files under config/www are served at /local without authentication, which
    is why the contents are redacted first. The same filename is reused on
    every export so repeated runs do not leave a pile behind.
    """
    export = await async_build_export(api, device_id)

    filename = f"tuya-inspector-{device_id}.json"
    directory = Path(hass.config.path("www"))
    path = directory / filename

    def _write() -> None:
        directory.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(export, indent=2, ensure_ascii=False), encoding="utf-8")

    await hass.async_add_executor_job(_write)
    _LOGGER.info("Wrote device export to %s", path)

    url = f"/local/{filename}"

    # An anchor with target="_blank" rather than a markdown link: the frontend
    # is a single page app and routes a plain relative link through its own
    # router, which does not know this path and lands on the dashboard.
    async_create_notification(
        hass,
        (
            f"The export for **{title}** is ready.\n\n"
            f'<a href="{url}" target="_blank" rel="noreferrer" download>'
            f"Download it</a> and attach it to your issue.\n\n"
            f"If the link does nothing, open this address directly:\n\n"
            f"`{url}`\n\n"
            "The file contains only this device's description. Local keys, "
            "account identifiers, your IP address and coordinates have been "
            "removed."
        ),
        title="Tuya Device Inspector",
        notification_id=f"{DOMAIN}_{device_id}",
    )

    return url